name: OpenAPI diff with OpenAPITools/openapi-diff

# Run breaking change check (with OpenAPITools/openapi-diff) https://github.com/OpenAPITools/openapi-diff
# https://github.com/swimmwatch/openapi-diff-action

on: 
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  run_number: ${GITHUB_RUN_NUMBER}

permissions:
  checks: write

jobs:

  openapitoools-openapi-diff:
    name: Breaking Change Check with OpenAPITools/openapi-diff
    runs-on: ubuntu-latest
    steps:
      - name: Checkout out pr branch
        uses: actions/checkout@v3
        with:
          path: head
      - name: Check out main branch
        uses: actions/checkout@v3
        with:
          ref: main
          path: base
      - name: View working folder
        run: |
          ls -lash
          tree
      - name: "Run breaking change check (with OpenAPITools/openapi-diff)"
        id: diff_state
        uses: swimmwatch/openapi-diff-action@v1.0.1
        with:
          old-spec: base/api-definitions/product-catalog-api.oas.yaml
          new-spec: head/api-definitions/product-catalog-api.oas.yaml
          json: "diff.json"
          markdown: "diff.md"
          text: "diff.txt"
      - name: "Upload OpenAPI-diff report as Github Artifact"
        uses: actions/upload-artifact@v3
        with:
          name: diff-reports
          path: |
            ./diff.md
            ./diff.json
            ./diff.txt
      - name: "Fail if breaking change"
        if: ${{ steps.diff_state.outputs.state == 'incompatible' }} 
        uses: actions/github-script@v6
        with:
          script: |
            core.setFailed("Failed due to breaking change! Diff state - ${{ steps.diff_state.outputs.state }} ")


      